# Site settings
title: ""
email: hamzauddin54@gmail.com
description: ""
baseurl: ""
url: "https://hamzauddin-siddiqui.github.io"

# Social media and contact
github_username: Hamzauddin-Siddiqui
linkedin_username: hamzauddin-siddiqui-786180175

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Minima theme customization
minima:
  skin: auto
  
# Completely disable default navigation
show_excerpts: false
header_pages: []

# Remove all other social links and author info
twitter_username: ""
author: ""

# Exclude files
exclude:
  - node_modules/
  - vendor/

# Page defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
